name: Integración de Pipeline Continua (CI)

on:
  push:
   branches: [ "main" , "develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4
      with:
        # IMPORTANTE: Necesitamos depth: 0 para que SonarQube pueda leer todo el histórico de Git
        fetch-depth: 0

    - name: Configurar entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias de la aplicación
      run: |
        python -m pip install --upgrade pip --only-binary=:all:
        pip install -r requirements.txt --only-binary=:all:

    - name: Instalar herramientas de CI
      run: |
        pip install \
          pytest==9.0.3 \
          httpx==0.28.1 \
          pip-audit==2.9.0 \
          pytest-cov==6.0.0 \
          --only-binary=:all:

    - name: Ejecutar Pruebas Unitarias (Pytest)
      env:
        PYTHONPATH: .
      run: |
        python -m pytest tests/test_main.py --cov=. --cov-report=xml

    - name: Análisis de Vulnerabilidades OWASP (pip-audit)
      run: |
        # Escaneamos el entorno de Python buscando fallos de seguridad en las librerías
        pip-audit --desc
    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Análisis Estático de Código con SonarQube
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        # El parámetro wait=false hace que el análisis sea ASÍNCRONO (requisito de Fabián)
        args: >
          -Dsonar.projectKey=MarcosFaura_Proyecto-devops-real
          -Dsonar.organization=marcosfaura
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.qualitygate.wait=false

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Iniciar sesión en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Calcular Versión Semántica Dinámica
      id: vars
      run: |
        # Contamos cuántos commits llevas acumulados en Git
        COUNT=$(git rev-list --count HEAD)
        
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "VERSION_TAG=1.0.${COUNT}" >> $GITHUB_ENV
        else
          echo "VERSION_TAG=1.0.${COUNT}-SNAPSHOT" >> $GITHUB_ENV
        fi

    - name: Compilar y subir imagen
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/proyecto-real:${{ env.VERSION_TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/proyecto-real:latest
