name: Integración de Pipeline Continua (CI)

on:
  push:
   branches: [ "main" , "develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4
      with:
        # IMPORTANTE: Necesitamos depth: 0 para que SonarQube pueda leer todo el histórico de Git
        fetch-depth: 0

    - name: Configurar entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias de pruebas
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pytest httpx pip-audit

    - name: Ejecutar Pruebas Unitarias (Pytest)
      env:
        PYTHONPATH: .
      run: |
        pytest tests/test_main.py

    - name: Análisis de Vulnerabilidades OWASP (pip-audit)
      run: |
        # Escaneamos el entorno de Python buscando fallos de seguridad en las librerías
        pip-audit --desc on

    - name: Análisis Estático de Código con SonarQube
      uses: sonarsource/sonarqube-scan-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        # El parámetro wait=false hace que el análisis sea ASÍNCRONO (requisito de Fabián)
        args: >
          -Dsonar.projectKey=MarcosFaura_Proyecto-devops-real
          -Dsonar.organization=marcosfaura
          -Dsonar.qualitygate.wait=false

    - name: Ejecutar Semantic Release (Calcular versión SemVer)
      id: semantic
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Llave interna automática de GitHub
      with:
        branch: main
        extra_plugins: |
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Iniciar sesión en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Compilar y subir imagen
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/proyecto-real:${{ steps.semantic.outputs.new_release_version || '1.0.0-draft' }}
          ${{ secrets.DOCKERHUB_USERNAME }}/proyecto-real:latest
